######################## default configuration ####################
baseURL = "https://www.sharingspring.com/"
title = "SharingSpring"
theme = "port-hugo"
publishDir = "docs"

defaultContentLanguage = 'ko'   # 기본 언어 설정
hasCJKLanguage = true           # 한국어/중국어/일본어 줄바꿈/단어 계산 최적화

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################## language ###############################

[languages]
  # --------------------------
  # 한국어 설정 (기본)
  # --------------------------
  [languages.ko]
    languageName = "한국어"
    contentDir = "content"
    weight = 1
    
    # 한국어 메뉴
#    [[languages.ko.menu.main]]
#      name = "홈"
#      URL = "/"
#      weight = 1
    [[languages.ko.menu.main]]
      name = "상담사 소개"
      URL = "/#about"
      weight = 2
    [[languages.ko.menu.main]]
      name = "상담소 소개"
      URL = "/intro/"
      weight = 3
    [[languages.ko.menu.main]]
      name = "예약하기"        # ◀ 새로 추가된 메뉴
      URL = "/booking/"      # ◀ content/booking/ 폴더를 찾아감
      weight = 4
    [[languages.ko.menu.main]]
      name = "질문"
      URL = "/faq/"
      weight = 5
    [[languages.ko.menu.main]]
      name = "공지사항"
      URL = "/updates/" 
      weight = 6
    [[languages.ko.menu.main]]
      name = "EN"        # 영어로 전환하는 버튼
      URL = "/en/"      # 영어 사이트 경로
      weight = 10       # 맨 오른쪽에 배치

  # --------------------------
  # 영어 설정
  # --------------------------
  [languages.en]
    languageName = "English"
    contentDir = "content"
    weight = 2
    [languages.en.params]
      # 영어 페이지일 때 data/content_en.yml을 읽도록 파라미터 지정
      contentData = "content_en"

    # 영어 메뉴
#    [[languages.en.menu.main]]
#      name = "Home"
#      URL = "/en/"
#      weight = 1
    [[languages.en.menu.main]]
      name = "About Me"
      URL = "/en/#about"
      weight = 2
    [[languages.en.menu.main]]
      name = "Introduction"
      URL = "/en/intro/"
      weight = 3
    [[languages.en.menu.main]]
      name = "Book Now"#
      URL = "/en/booking/"
      weight = 4
    [[languages.en.menu.main]]
      name = "FAQ"
      URL = "/en/faq/"
      weight = 5
    [[languages.en.menu.main]]
      name = "Updates"
      URL = "/en/updates/"
      weight = 6
    [[languages.en.menu.main]]
      name = "한국어"        # 한국어로 전환하는 버튼
      URL = "/"         # 한국어 사이트 경로
      weight = 10

#################### default parameters ################################
[params]
copyright1 = "&copy; 2026 SharingSpring. All rights reserved."
#copyright2 = "This site is for informational purposes only and does not provide emergency services."
# Meta data
description = "Personal Portfolio"
author = "Michelle Park"
favicon = "images/ssssharingspring.png"
google_analytics = "G-09W53MHB2G"
logo_light = "images/sharingspring.png"
logo_dark = "images/sharingspring.png"

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

# [[params.social]]
# icon = "fab fa-instagram"
# link = "https://www.instagram.com/sharingspring"

# [[params.social]]
# icon = "fab fa-linkedin"
# link = "https://kr.linkedin.com/in/michellepark-sharingspring"

# [[params.social]]
# icon = "fab fa-threads"
# link = "https://www.threads.com/@sharingspring"

# [[params.social]]
# icon = "fas fa-envelope"
# link = "mailto:guster@burton.com"

############################# address ########################

[[params.remark]]
#remark1 = "온라인 상담을 진행 중입니다."
#remark2 = "Now taking online therapy sessions."

[[params.address]]
address = "심리상담소 봄나눔 | 서울 특별시 마포구 와우산로 105, 5층 242A호"
registnum = "대표자: 박우아 | 사업자등록번호: 673-04-03744"

contentDir = "content/english"
weight = 1
home = "Home"
